client: false
server: false
velociraptor_dir: /opt/velociraptor
velociraptor_config_dir: /etc/velociraptor
velociraptor_log_dir: /var/log/velociraptor
velociraptor_server_config: velociraptor.server.config.yml
velociraptor_admin_user: admin
velociraptor_admin_password: sec699
velociraptor_client_config: Velociraptor.config.yaml
velociraptor_msi_url_debian: https://github.com/Velocidex/velociraptor/releases/download/v0.75/velociraptor-v0.75.4-linux-amd64 
velociraptor_msi_url_rhel: https://github.com/Velocidex/velociraptor/releases/download/v0.75/velociraptor-v0.75.4-linux-amd64-musl
velociraptor_debian_file: velociraptor_debian 
velociraptor_rhel_file: velociraptor_rhel
_velociraptor_windows_dir: C:\Program Files\Velociraptor\
