---
- name: include linux debian client tasks
  import_tasks: linux_client_debian.yml
  tags:
    - debian_client

- name: include linux rhel client tasks
  import_tasks: linux_client_rhel.yml
  tags:
    - rhel_client

- name: include server tasks
  import_tasks: server.yml
  tags:
    - server