---
apt_dist_upgrade: true
install_docker: false
ufw_allowed_ports: []
# Example:
#  - { port: '80', proto: 'tcp' }
#  - { port: '443', proto: 'tcp' }
#  - { port: '1514', proto: 'tcp', from: '10.0.0.0/8' }
