galaxy_info:
  author: perfSONAR
  description: A perfSONAR role to install the perfsonar-testpoint bundle
  company: perfSONAR Project
  license: Apache 2.0

  min_ansible_version: 2.5

  platforms:
    - name: Rocky
      versions:
        - 8
        - 9
    - name: AlmaLinux
      versions:
        - 8
        - 9

  galaxy_tags:
    - networking
    - monitoring
    - perfsonar
    - network
    - metrics
    - performance

dependencies:
  - role: perfsonar-baseinstall-baremetal
