- name: Ensure Nmap is installed
  ansible.builtin.package:
    name: nmap
    state: present

- name: Perform an Nmap full scan and save results
  ansible.builtin.shell: >
    nmap -p- -T4 -A -v {{ internal_network_range }} > ~/nmap-scan.txt
  args:
    executable: /bin/bash
  register: nmap_result