---
fwports:
  - port: 443
    proto: tcp

  - port: 861
    proto: tcp

  - port: 8760-9960
    proto: tcp

  - port: 862
    proto: tcp

  - port: 18760-19960
    proto: tcp

  - port: 18760-19960
    proto: udp

  - port: 5890-5900
    proto: tcp

  - port: 5000
    proto: tcp

  - port: 5101
    proto: tcp

  - port: 5001
    proto: tcp

  - port: 5201
    proto: tcp

  - port: 123
    proto: udp