galaxy_info:
  author: unrccdc2026
  description: A perfSONAR role to install and configure web services on Rocky/AlmaLinux systems.

  galaxy_tags:
    - networking
    - monitoring
    - perfsonar
    - network
    - metrics
    - performance

dependencies:
  - role: perfsonar-baseinstall-baremetal
